### ISSUE TITLE
refuse to set unsafe header 'Content-Length'

### ISSUE THREAD

**Issue by isNeilLin** [chux0519/axios-request#3]
我在设置content-length的时候，遇到了拒绝设置不安全的请求头content-length这样的提示。我使用的是electron框架，chrome的内核。

**Comment by chux0519** [comment]
1. 浏览器禁止设置content-type实际上是一种安全策略，可以参考:https://gist.github.com/lfzark/e27ad15b9082fd9c77b1
2. 实际上现在浏览器发送表单是很容易的，你可以试试fetch，已经算是一种标准了，而且支持promise，参考：https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch#Headers
3. 注:之前讨论的问题是在服务端发送包含文件的表单，场景不太一样。
